### ISSUE TITLE
Norwegian (Norsk) <no-no.cfg>

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/EternoRest2000#26]
# Localization - ![Norsk][NO] Norwegian (Norsk) <no-no.cfg>

## GitHub

* [x] assign
  * [x] zer0Kerbal
  * [x] Repo Localization Project
  * [x] Label: type: localization
  * [x] Label: help-wanted
  * [x] Milestone: Localization - Master

### GameData

* [x] add  Localization\[no-no.cfg] 🗃️

### Translation

* [x] ![Norsk][NO] Norwegian (Norsk) <no-no.cfg>

### Documentation

* [x] Update [readme.md] 🔢
* [x] Update [release.md] 🧾

### Wiki

* [x] Update docs/[localization.md]

## Update Social Media

* [x] GitHub (automated) (zer0Kerbal/zer0Kerbal)
* [x] CurseForge
* [x] Reddit
* [x] Twitter @zer0Kerbal
* [x] Forum
* [x] Patreon
* [x] SpaceDock
* [x] CKAN (automated)

[lclztn]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/readme.md  "Localization"
[qs]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/quickstart.md "Quick Start"

[NO]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/master/img/NO.png "Norsk"

this file: © All Rights Reserved by zer0Kerbal

**Comment by tplive** [comment]
I can work on this! 👍🏽
