### ISSUE TITLE
Contract to Launch a dead crew member into space

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/EternoRest2000#50]
> * Contract looks for dead crew members and selects one at random to send into space.
> * On successful completion of the orbit the dead Kerbal has it's type changed from crew to unowned.
> * This has the effect of making the dead Kerbal invisible in the astronaut complex and unelectable for future runs of this contract
> * The Kerbal still remains in the roster in the persistent.sfs file.
> * Use as is or modify to suit your requirements.

@caerfinon thank you - especially valuable since I haven't a clue how to write contracts for KSP. :D

_Originally posted by @zer0Kerbal in https://github.com/zer0Kerbal/EternoRest2000/issues/47#issuecomment-1284724923_

**Comment by zer0Kerbal** [comment]
@caerfinon

**Comment by caerfinon** [comment]
glad i could help

**Comment by zer0Kerbal** [comment]
> glad i could help

should see the comments on the two reddit postings. 😀

[most recent post with the contract](https://www.reddit.com/r/KerbalSpaceProgram/comments/y9i3ul/recently_dug_12990adoption_thank_you_aphtonites/?utm_source=share&utm_medium=web2x&context=3)
[initial post](https://www.reddit.com/r/KerbalSpaceProgram/comments/ydov4y/recently_dug_1300release_caerfinons_contract/?utm_source=share&utm_medium=web2x&context=3)
